### ISSUE TITLE
When the value is changed the component does not render properly

### ISSUE THREAD

**Issue by d2ni3l** [ziaulhoque24/react-rating-star-with-type#3]
const [starRating, setRating] = useState<number>(4);

<ReactStars
              onChange={(val) => {
                setRating(val);
              }}
              value={starRating}
              classNames='space-x-1'
              isEdit={true}
              activeColors={["red", "orange", "#FFCE00", "#FFCE00", "#FFE70F"]}
              size={18}
            />

<button onClick={() => {setRating(5)}}>change rating to 0</button>

The value is changed but the stars continue to show 4.

Am i doing something wrong?

**Comment by ziaulhoque24** [comment]
you can't change value from outside like this <button onClick={() => {setRating(5)}}>.
you have to change value by click on star

**Comment by ziaulhoque24** [comment]
fixed. now enjoy!!
